name: cleanup

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Remove old workflows
        run: |
          cd .github/workflows

          rm -f Vite_deploy2.yml
          rm -f auto-rebuild.yml
          rm -f deploy.Yml
          rm -f deploy2.yml
          rm -f final-cleaner.yml
          rm -f fix_rebuilder.yml
          rm -f orchestrator.yml
          rm -f repository-merger.yml
          rm -f vite_deploy.yml

      - name: Commit cleanup
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add .
          git commit -m "cleanup workflows" || echo "nothing to commit"
          git push
